<?php $this->render('shared/header', ['titulo' => $titulo ?? 'Restriccion']); $this->render('shared/sidebar_admin'); $esEdicion = !empty($restriccion['id_restriccion']); $dias = ['','LUNES','MARTES','MIERCOLES','JUEVES','VIERNES','SABADO','DOMINGO']; ?>
<div class="header-acciones"><h1><?= htmlspecialchars($titulo) ?></h1><a class="btn-demo" href="?ruta=admin/academico/restricciones">Volver</a></div>
<div class="panel"><form method="POST" action="?ruta=admin/academico/restricciones/<?= $esEdicion ? 'actualizar' : 'guardar' ?>" class="responsive-form-grid">
<?php if ($esEdicion): ?><input type="hidden" name="id_restriccion" value="<?= (int)$restriccion['id_restriccion'] ?>"><?php endif; ?>
<div class="form-group"><label>Tipo</label><select class="form-control" name="tipo"><?php foreach (['DOCENTE','ESPACIO','HORARIO','OTRO'] as $t): ?><option value="<?= $t ?>" <?= (($restriccion['tipo'] ?? 'DOCENTE') === $t) ? 'selected' : '' ?>><?= $t ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Periodo</label><select class="form-control" name="id_periodo"><option value="">General</option><?php foreach ($periodos as $p): ?><option value="<?= (int)$p['id_periodo'] ?>" <?= ((int)($restriccion['id_periodo'] ?? 0) === (int)$p['id_periodo']) ? 'selected' : '' ?>><?= htmlspecialchars($p['codigo']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Docente</label><select class="form-control" name="id_docente"><option value="">No aplica</option><?php foreach ($docentes as $d): ?><option value="<?= (int)$d['id_docente'] ?>" <?= ((int)($restriccion['id_docente'] ?? 0) === (int)$d['id_docente']) ? 'selected' : '' ?>><?= htmlspecialchars($d['apellido'] . ' ' . $d['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Espacio</label><select class="form-control" name="id_espacio"><option value="">No aplica</option><?php foreach ($espacios as $e): ?><option value="<?= (int)$e['id_espacio'] ?>" <?= ((int)($restriccion['id_espacio'] ?? 0) === (int)$e['id_espacio']) ? 'selected' : '' ?>><?= htmlspecialchars(($e['sede_nombre'] ?? '') . ' / ' . ($e['bloque_nombre'] ?? '') . ' / ' . $e['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Dia</label><select class="form-control" name="dia_semana"><?php foreach ($dias as $d): ?><option value="<?= $d ?>" <?= (($restriccion['dia_semana'] ?? '') === $d) ? 'selected' : '' ?>><?= $d ?: 'No aplica' ?></option><?php endforeach; ?></select></div>
<div class="form-group"><label>Hora inicio</label><input type="time" class="form-control" name="hora_inicio" value="<?= htmlspecialchars($restriccion['hora_inicio'] ?? '') ?>"></div>
<div class="form-group"><label>Hora fin</label><input type="time" class="form-control" name="hora_fin" value="<?= htmlspecialchars($restriccion['hora_fin'] ?? '') ?>"></div>
<div class="form-group"><label>Estado</label><select class="form-control" name="estado"><?php foreach (['ACTIVA','INACTIVA'] as $e): ?><option value="<?= $e ?>" <?= (($restriccion['estado'] ?? 'ACTIVA') === $e) ? 'selected' : '' ?>><?= $e ?></option><?php endforeach; ?></select></div>
<div class="form-group" style="grid-column:1/-1;"><label>Descripcion</label><input class="form-control" name="descripcion" value="<?= htmlspecialchars($restriccion['descripcion'] ?? '') ?>"></div>
<div class="form-group" style="grid-column:1/-1;"><button class="btn-primario">Guardar restriccion</button></div>
</form></div><?php $this->render('shared/footer'); ?>
