<?php $this->render('shared/header', ['titulo' => $titulo ?? 'Asignatura']); $this->render('shared/sidebar_admin'); $this->render('shared/tabs_academico', ['activo' => 'asignaturas']); $esEdicion = !empty($asignatura['id_asignatura']); ?>
<div class="form-shell"><div class="brand-form-card brand-form-card-wide"><div class="form-entity-icon"><i class="fa-solid fa-book"></i></div><h1><?= htmlspecialchars($titulo) ?></h1><p>Define el componente curricular, su area academica y los programas asociados.</p><form method="POST" action="?ruta=admin/academico/asignaturas/<?= $esEdicion ? 'actualizar' : 'guardar' ?>" class="brand-form-grid">
<?php if ($esEdicion): ?><input type="hidden" name="id_asignatura" value="<?= (int)$asignatura['id_asignatura'] ?>"><?php endif; ?>
<div class="form-group input-icon"><label>Codigo</label><i class="fa-solid fa-barcode"></i><input class="form-control" name="codigo" required value="<?= htmlspecialchars($asignatura['codigo'] ?? '') ?>"></div><div class="form-group input-icon"><label>Nombre</label><i class="fa-solid fa-book-open"></i><input class="form-control" name="nombre" required value="<?= htmlspecialchars($asignatura['nombre'] ?? '') ?>"></div>
<div class="form-group input-icon"><label>Creditos</label><i class="fa-solid fa-star"></i><input type="number" min="1" class="form-control" name="creditos" required value="<?= htmlspecialchars($asignatura['creditos'] ?? '3') ?>"></div><div class="form-group input-icon"><label>Tipo</label><i class="fa-solid fa-layer-group"></i><input class="form-control" name="tipo" value="<?= htmlspecialchars($asignatura['tipo'] ?? '') ?>"></div>
<div class="form-group input-icon"><label>Area academica</label><i class="fa-solid fa-shapes"></i><select class="form-control" name="id_area_academica"><option value="">Sin area</option><?php foreach (($areas ?? []) as $area): ?><option value="<?= (int)$area['id_area_academica'] ?>" <?= ((int)($asignatura['id_area_academica'] ?? 0) === (int)$area['id_area_academica']) ? 'selected' : '' ?>><?= htmlspecialchars($area['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="form-group input-icon"><label>Estado</label><i class="fa-solid fa-toggle-on"></i><select class="form-control" name="estado"><?php foreach (['ACTIVO','INACTIVO'] as $e): ?><option value="<?= $e ?>" <?= (($asignatura['estado'] ?? 'ACTIVO') === $e) ? 'selected' : '' ?>><?= $e ?></option><?php endforeach; ?></select></div>
<div class="form-group" style="grid-column:1/-1;"><label>Programas</label><select class="form-control" name="programas[]" multiple size="8"><?php foreach ($programas as $p): ?><option value="<?= (int)$p['id_programa'] ?>" <?= in_array((int)$p['id_programa'], $programasAsignados ?? [], true) ? 'selected' : '' ?>><?= htmlspecialchars($p['nombre']) ?></option><?php endforeach; ?></select></div>
<div class="form-actions" style="grid-column:1/-1;"><button class="btn-primario"><i class="fa-solid fa-check"></i> Guardar</button><a class="btn-outline" href="?ruta=admin/academico/asignaturas"><i class="fa-solid fa-arrow-left"></i> Cancelar</a></div>
</form></div></div><?php $this->render('shared/footer'); ?>
